#include "ArbolAVL.h"

#include <iostream>
using namespace std;

int main(){
    ArbolAVL<int> arbol;
    /*
    arbol.insertarNodo(40);
    arbol.insertarNodo(40);*/
    
    arbol.insertarNodo(50);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(30);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(70);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(20);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(40);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(60);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(80);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(10);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(25);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(35);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(70);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(70);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(90);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(5);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(30);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(30);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(15);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(27);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(80);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(80);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(45);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(65);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(10);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(10);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(50);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(50);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(95);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(20);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(20);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(12);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(70);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(70);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(55);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(25);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(25);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(90);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(90);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(15);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.insertarNodo(15);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
    arbol.eliminarNodo(80);
    cout<<"\nEl recorrido inOrden es: \n";
    arbol.inOrden();
    cout<<"\nEl recorrido posOrden es: \n";
    arbol.posOrden();
    cout<<"\nEl recorrido preOrden es: \n";
    arbol.preOrden();
    cout<<"\nEl recorrido levelOrden es: \n";
    arbol.nivelesOrden();
    cout<<"\nAltura: "<<arbol.altura();
}
